- Added delete function in the backend and frontend
Hirnstromwelle/Sprite-Branch pull request #10
Opened 2023-11-30 10:58 UTC by Hirnstromwelle

- Created controller, service, and repository for the delete functionality.
- Added integration tests to ensure the delete function works as expected.
- Added unit tests to cover the new components and functions.
- Created new components in the frontend: 'ReadyPage' and 'CharacterSelectionPage'.
- Performed code cleanup and organization.

2023-11-30 11:17 UTC, lostspezi requested changes
Sieht schon ganz gut aus, habe aber ein paar Anmerkungen :) _Außerdem solltest du deinen CodeSmell mal checken;-)

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/controllers/ItemController.java
> +        }
Unnötig. Du kannstz einfach die delete methode aus dem Service aufrufen ohne try catch. Auch brauchst du kein ResponseEntity. Du kannst den Endpunkt mit @ResponseStatus annotieren. Sollte in Fehler auftreten, sollte er im service geschmissen werden und dann über einen ExceptionHandler an den User rausgegeben werden

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/controllers/SaveGameController.java
> +        }
selbe gilt hier

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/repositorys/SaveGameRepository.java
> +    Optional<SaveGame> findBySaveId(String saveId);
Es gibt schon die methode findById, warum defenierst du sie hier noch mal?

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/services/HeroService.java
> +    }
Hier solltest du überprüfen ob es den Hero anhand der Id gibt. Wenn ja, dann löschen, wenn nein, dann Exception

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/services/SaveGameService.java
> +        saveGameOptional.ifPresent(saveGameRepository::delete);
hier machst du es ja auch

2023-11-30 11:17 UTC, MoinMarcell commented on backend/src/test/java/com/github/hirnstromwelle/spritebranch/controllers/HeroControllerTest.java
> +        String heroJson = "{\"id\":null,\"name\":\"TestHeroToDelete\",\"itemIds\":[]}";
ObjectMapper nutzen, dann hast du nicht solche komische konstrukte ;-)

2023-12-01 09:43 UTC, BrainCodeJockey commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/controllers/ItemController.java
> +        }
Guter Punkt, hab ich geändert.

2023-12-01 10:12 UTC, Hirnstromwelle commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/repositorys/SaveGameRepository.java
> +    Optional<SaveGame> findBySaveId(String saveId);
Wiederum gute Punkt, ist geändert.

2023-12-01 10:20 UTC, BrainCodeJockey commented on backend/src/main/java/com/github/hirnstromwelle/spritebranch/services/HeroService.java
> +    }
Stimmt, angepasst.

2023-12-01 10:37 UTC, Hirnstromwelle commented on backend/src/test/java/com/github/hirnstromwelle/spritebranch/controllers/HeroControllerTest.java
> +        String heroJson = "{\"id\":null,\"name\":\"TestHeroToDelete\",\"itemIds\":[]}";
Ehrlich gesagt, finde ich Json ganz toll. ^^ Hab den Test jetzt auf ObjectMapper geändert.

2023-12-01 13:20 UTC, mpagels approved these changes

2023-12-01 13:24 UTC, lostspezi requested changes
Soweit sieht es sehr gut aus ;-) Aber du hast einen Codesmell immer noch und eine kleine Anmerkung / Frage zu einer Dependency

2023-12-01 13:24 UTC, MoinMarcell commented on backend/pom.xml
> +        </dependency>
wofür? Ist schon Teil von Spring Boot

2023-12-01 14:59 UTC, Hirnstromwelle commented
Jetzt aber is alles jute : )

2023-12-01 15:01 UTC, MoinMarcell approved these changes
lgtm!:)

2023-12-01 15:06 UTC, merged