-Refactored the entire frontend codebase.
Hirnstromwelle/Sprite-Branch pull request #13
Opened 2023-12-08 10:55 UTC by Hirnstromwelle

-Refactored the entire frontend codebase
-Performed CSS styling
-Updated the useEffect for state management
-Created a hook to ensure the location is always displayed

2023-12-08 11:05 UTC, mpagels requested changes
This pr is too big to review. 1000 changes? 37 files? Different topics that have changes.
Please split this pr in at least 4 different small pull request with changes that has one topic in common.

E.g.:
PR1 -> only changes that are relating to the refactoring
PR2 -> only changes that are relating to the css styling
PR3 -> only changes that are relating to the useEffect Update
PR4 -> only changes that are relating to the global state update

This way you make sure, that the reviewer can concentrate on only one thing and the cognitive overload is not that much. And the changes are higher, you get a review, if the changes are small. Like only 4 files and 50 lines of code to review instead of 37 files and 1000 changes...

2023-12-08 12:07 UTC, Hirnstromwelle commented
> This pr is too big to review. 1000 changes? 37 files? Different topics that have changes. Please split this pr in at least 4 different small pull request with changes that has one topic in common.
> 
> E.g.: PR1 -> only changes that are relating to the refactoring PR2 -> only changes that are relating to the css styling PR3 -> only changes that are relating to the useEffect Update PR4 -> only changes that are relating to the global state update
> 
> This way you make sure, that the reviewer can concentrate on only one thing and the cognitive overload is not that much. And the changes are higher, you get a review, if the changes are small. Like only 4 files and 50 lines of code to review instead of 37 files and 1000 changes...

How do I split this large commit into smaller pushes?

2023-12-08 14:06 UTC, Hirnstromwelle commented
The pull request has been split into three pieces.

2023-12-09 17:09 UTC, AljoschaNy commented on frontend/src/components/DeleteSaveGame/DeleteSaveGame.tsx
> +    onDeleteHero: (heroId: string) => void;
ist nur ein Hinweis: du hast bisher ausschließlich type genutzt. Deswegen würde ich dieses Interface noch zu einem type umwandeln und zu deiner types.ts hinzufügen

2023-12-09 17:27 UTC, AljoschaNy commented on frontend/src/components/SceneLayout/SceneLayout.tsx
> +}
Wie vorhin erwähnt, ich würde bei type bleiben und deine ganzen types in deiner zentralen types.ts verwalten

2023-12-09 17:50 UTC, AljoschaNy requested changes
Soweit sieht alles Top aus. Statt interface würde ich allerdings type nutzen.

2023-12-09 17:50 UTC, AljoschaNy commented on frontend/src/App.tsx
> +        }
Ich würde den Funktionsaufruf in einen Else Block einfügen. So gibt es im Fall, dass wenn shouldUpdate true ist, keine doppelten API-Aufrufe
```suggestion
        if (shouldUpdate) {
            fetchDataAndUpdate()
                .then(() => {
                    setShouldUpdate(false);
                })
                .catch((error) => {
                    console.error('Fehler beim Laden der Daten:', error);
                });
        } else {
         fetchDataAndUpdate()
            .catch((error) => {
                console.error('Fehler beim Laden der Daten:', error);
            });
        }
```

2023-12-09 18:01 UTC, AljoschaNy approved these changes

2023-12-09 18:01 UTC, AljoschaNy commented
LGTM, top!

2023-12-09 18:01 UTC, merged